name       : The-Powder-Toy
version    : 93.3
release    : 5
source     :
    - https://github.com/ThePowderToy/The-Powder-Toy/archive/v93.3.tar.gz : 6c5f5914e4ae0ac8500c7203ec69517a2fd4380dece6b33247ed719aa12e074e
license    : GPL-3.0-only
component  : games
summary    : The Powder Toy is a desktop version of the classic 'falling sand' physics sandbox, it simulates air pressure and velocity as well as heat.
description: |
    Have you ever wanted to blow something up? Or maybe you always dreamt of operating an atomic power plant? Do you have a will to develop your own CPU? The Powder Toy lets you to do all of these, and even more!
    The Powder Toy is a free physics sandbox game, which simulates air pressure and velocity, heat, gravity and a countless number of interactions between different substances! The game provides you with various building materials, liquids, gases and electronic components which can be used to construct complex machines, guns, bombs, realistic terrains and almost anything else. You can then mine them and watch cool explosions, add intricate wirings, play with little stickmen or operate your machine. You can browse and play thousands of different saves made by the community or upload your own – we welcome your creations!
    There is a Lua API – you can automate your work or even make plugins for the game. The Powder Toy is free and the source code is distributed under the GNU General Public License, so you can modify the game yourself or help with development.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(lua-5.1)
    - pkgconfig(sdl)
    - pkgconfig(x11)
    - bzip2-devel
    - scons
build      : |
    scons
install    : |
    install -Dm00755 build/powder64 %installroot%/usr/bin/powder
    install -Dm00644 resources/powder.desktop %installroot%/usr/share/applications/powder.desktop
    install -Dm00644 resources/icon/powder-256.png %installroot%/usr/share/pixmaps/powder.png
    install -Dm00644 resources/powder.appdata.xml $installdir/usr/share/metainfo/powder.appdata.xml
